import type { Gl2Port, Gl2Caps, FBOPrec, PooledFBO, Gl2Texture, Gl2TileArena, Gl2DrawSpec, TexUploadFormat } from "../common/gl2-port.ts";
export declare class BrowserTileArena implements Gl2TileArena {
    readonly kind: "arena";
    readonly tileSize: number;
    private _gl;
    private _tex;
    private _capacity;
    private _disposed;
    private _onDisposed;
    constructor(gl: WebGL2RenderingContext, tileSize: number, initialSlices: number, onDisposed?: () => void);
    get capacity(): number;
    get texture(): WebGLTexture;
    private _aliveGuard;
    private _alloc;
    recreate(newCapacity: number): void;
    uploadSlice(slice: number, pixels: Uint8Array): void;
    copySlice(from: PooledFBO, slice: number, srcX: number, srcY: number, w: number, h: number): void;
    dispose(): void;
}
export declare class BrowserGl2Port implements Gl2Port {
    readonly canvas: HTMLCanvasElement | OffscreenCanvas;
    readonly gl: WebGL2RenderingContext;
    readonly caps: Gl2Caps;
    private _programs;
    private _programSrc;
    private _pending;
    private _pendingTimer;
    private _warmFailed;
    private _parallelExt;
    private _fboPool;
    private _quad;
    private _instVao;
    private _instBuf;
    private _ph2d;
    private _phArr;
    private _invalidated;
    private _lost;
    private _gen;
    constructor(canvas: HTMLCanvasElement | OffscreenCanvas);
    get isLost(): boolean;
    get generation(): number;
    onInvalidated(cb: () => void): void;
    program(name: string, vert?: string, frag?: string): void;
    warmProgram(name: string, vert: string, frag: string): void;
    private _schedulePendingPoll;
    private _pollPending;
    private _meta;
    private _compile;
    private _startLink;
    private _finishLink;
    private _shader;
    fboPoolHas(w: number, h: number, prec: FBOPrec): boolean;
    get fboPoolBudgetBytes(): number;
    borrowFBO(w: number, h: number, prec?: FBOPrec): PooledFBO;
    returnFBO(f: PooledFBO): void;
    private _fboBytes;
    private _poolBytes;
    get fboPoolStats(): {
        count: number;
        bytes: number;
    };
    clearPool(): void;
    clearFBO(f: PooledFBO, rgba: [number, number, number, number]): void;
    private _createFBO;
    private _quadVAO;
    private _instancedVAO;
    draw(spec: Gl2DrawSpec): void;
    drawInstanced(spec: Gl2DrawSpec, instances: Float32Array, count: number): void;
    private _drawCommon;
    private _setUniforms;
    private _bindTextures;
    private _resolve2d;
    private _placeholder2d;
    private _placeholderArr;
    readPixels(src: PooledFBO, x: number, y: number, w: number, h: number): Uint8Array;
    createTexture(): Gl2Texture;
    uploadTexture(tex: Gl2Texture, format: TexUploadFormat, w: number, h: number, data: ArrayBufferView): void;
    deleteTexture(tex: Gl2Texture): void;
    private _arenas;
    createTileArena(tileSize: number, initialSlices: number): Gl2TileArena;
    get arenaStats(): {
        count: number;
        bytes: number;
    };
    private _rebuildAfterRestore;
}
